name: Pull Request
on:
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js (${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Install Playwright
        uses: borales/actions-yarn@v4
        with:
          cmd: install:playwright
      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: test
