name: Pull Request
on:
  pull_request:
    branches:
      - '*'
jobs:
  formulas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.5]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js (${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: workspace @tss-calculator/formulas lint
      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: workspace @tss-calculator/formulas test
  web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.5]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js (${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Prepare
        uses: borales/actions-yarn@v4
        with:
          cmd: workspace @tss-calculator/web install:playwright
      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: workspace @tss-calculator/web lint
      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: workspace @tss-calculator/web test
